[opener]
edit = [ { run = 'micro "$@"', block = true } ]

[preview]
max_width = 1000
max_height = 1000
image_filter = "lanczos3"
image_quality = 90

[manager]
ratio          = [ 1, 3, 4 ] # Esto da el ancho a la previsualizaci√≥n
show_hidden    = false
show_symlink   = true
