# Usar formato de una sola línea con un diseño de "pills"
format = """
[░▒▓](#83a598)\
[ 󰣇 ](bg:#83a598 fg:#090618)\
[](fg:#83a598 bg:#3c3836)\
$directory\
[](fg:#3c3836 bg:#fabd2f)\
$git_branch\
$git_status\
[](fg:#fabd2f bg:#8ec07c)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#8ec07c bg:#06080a)\
$character"""

# Configuración de los módulos
[directory]
style = "bg:#3c3836 fg:#ebdbb2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:#fabd2f fg:#090618"
# Eliminamos los corchetes dobles innecesarios que causaban el error
format = "[$symbol$branch]($style)"

[git_status]
style = "bg:#fabd2f fg:#090618"
# Corregido el escape de la barra invertida y el anidamiento
format = "[($all_status$ahead_behind)]($style)"

[nodejs]
symbol = " "
style = "bg:#8ec07c fg:#090618"
format = "[ $symbol($version) ]($style)"

[rust]
symbol = " "
style = "bg:#8ec07c fg:#090618"
format = "[ $symbol($version) ]($style)"

[character]
success_symbol = "[ 󰁔 ](bold fg:#83a598)"
error_symbol = "[ 󰁔 ](bold fg:#fb4934)"
